name: Publish
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Pull repo
        uses: actions/checkout@master
      - name: Upload package
        uses: bartmachielsen/pip-upload-action@master
        with:
          username: '__token__'
          password: ${{ secrets.PIP_PASSWORD }}